[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "both"
build-mode = "both"
version = "latest"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
apkmirror-arch = "both"
version = "latest"
included-patches = "sim-spoof"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"

